// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package myfirstmodule.actions;

import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;

public class StringToLong extends CustomJavaAction<java.lang.Long>
{
	private final java.lang.String inputString;

	public StringToLong(
		IContext context,
		java.lang.String _inputString
	)
	{
		super(context);
		this.inputString = _inputString;
	}

	@java.lang.Override
	public java.lang.Long executeAction() throws Exception
	{
		// BEGIN USER CODE
        try {
            return Long.parseLong(inputString);
        } catch (NumberFormatException e) {
            // Handle the exception, perhaps log it or return a default value
            return null;
        }
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "StringToLong";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
