// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
import "mx-global";
import { Big } from "big.js";

// BEGIN EXTRA CODE
// END EXTRA CODE

/**
 * @param {string} demandID
 * @param {string} pageName
 * @returns {Promise.<string>}
 */
export async function GetURLParameter(demandID, pageName) {
	// BEGIN USER CODE
    const urlParams = new URLSearchParams(window.location.search);
    const id = urlParams.get(demandID);
    const page = urlParams.get(pageName);
    if (id && page) {
        return `${page}?id=${id}`;
    } else {
        throw new Error("Required parameters not found in the URL");
    }
	// END USER CODE
}
