// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
import "mx-global";
import { Big } from "big.js";

// BEGIN EXTRA CODE
// END EXTRA CODE

/**
 * @returns {Promise.<void>}
 */
export async function JavaScript_action_deleteFile2() {
	// BEGIN USER CODE
    let fileInput = document.getElementById('myfile1');
    if (fileInput) { // Ensure the file input element exists
        fileInput.value = ''; // Clear the file input
        fileInput.style.display = 'none'; // Hide the file input
    } else {
        console.warn('File input element with id "myfile" not found.');
    }
	// END USER CODE
}
