eureka:
   instance:
      hostname: config-server
   client:
      service-url:
         defaultZone: http://discovery:8761/eureka


server:
   port: 8082
spring:
   application:
      name: auth
   datasource:
      driver-class-name: org.postgresql.Driver
      url: jdbc:postgresql://postgres:5433/RNEdb?autoReconnect=true&useSSL=false&createDatabaseIfNotExist=true
      username: postgres
      password: youssef31
   jpa:
      hibernate:
         ddl-auto: update
      database: postgresql
      database-platform: org.hibernate.dialect.PostgreSQLDialect

management:
   tracing:
      sampling:
         probability: 1.0