eureka:
   instance:
      hostname: localhost
   client:
      service-url:
         defaultZone: http://localhost:8761/eureka


server:
   port: 8081
spring:
   application:
      name: referentiel
   datasource:
      driver-class-name: org.postgresql.Driver
      url: jdbc:postgresql://localhost:5433/RNEdb?autoReconnect=true&useSSL=false&createDatabaseIfNotExist=true&currentSchema=referentiel
      username: postgres
      password: Zaineb123


   jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        default_schema: referentiel
    database-platform: org.hibernate.dialect.PostgreSQLDialect

management:
   tracing:
      sampling:
         probability: 1.0