spring:
   application:
      name: referentiel
   config:
      import: optional:configserver:http://localhost:8888
   security:
      oauth2:
         resourceserver:
            jwt:
               issuer-uri: http://localhost:8080/realms/RNE
               jwk-set-uri: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/certs

jwt:
   auth:
      converter:
         resource-id: rne-rest-api
         principle-attribute: preferred_username